name: 03 - Run Basic Schema Stream

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: Image URL
        required: true
        default: "images/ps-finished.png"
      duration:
        description: 'Number of job duration in ms'
        required: true
        default: '500'
      x:
        description: 'Number of cells on x-Axis'
        required: true
        default: '4'
      y:
        description: 'Number of cells on y-Axis'
        required: true
        default: '3'
      pixel-x:
        description: 'Number of pixels on x-Axis'
        required: true
        default: '800'
      pixel-y:
        description: 'Number of pixels on y-Axis'
        required: true
        default: '600'
      repetitions:
        description: 'Number of matrix cell render cycles'
        required: true
        default: '2'
      repetition-delay:
        description: 'Wait time in ms between render cycles'
        required: true
        default: '30000'
      connections-per-cell:
        description: 'connections per matrix cell'
        required: true
        default: '1'

jobs:

  generate-matrix:
    runs-on: ubuntu-latest
    name: "Generate matrix job specs"
    outputs:
      x: ${{ steps.generate-matrix.outputs.x }}
      y: ${{ steps.generate-matrix.outputs.y }}
    steps:
      - name: generate-matrix
        id: generate-matrix
        run: |
          echo "::set-output name=x::[`seq -s , ${{ github.event.inputs.x }}`]"
          echo "::set-output name=y::[`seq -s , ${{ github.event.inputs.y }}`]"

  enter-matrix:
    name: "Render Matrix Cell"
    runs-on: ubuntu-latest
    needs: [generate-matrix]
    container:
      image: ghcr.io/jonico/actions-runner:ps
      options: --user root

    strategy:
      fail-fast: false
      #max-parallel: 16
      matrix:
        x: ${{ fromJson(needs.generate-matrix.outputs.x) }}
        y: ${{ fromJson(needs.generate-matrix.outputs.y) }}
        
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Stream pixels into PlanetScale DB
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          MY_DB_URL: ${{secrets.MY_DB_URL}}
        run: python3 render-matrix-cell.py --max-x='${{github.event.inputs.pixel-x}}' --max-y='${{github.event.inputs.pixel-y}}' --job-x='${{matrix.x}}' --job-y='${{matrix.y}}' --max-job-x='${{github.event.inputs.x}}' --max-job-y='${{github.event.inputs.y}}' --duration='${{github.event.inputs.duration}}' --environment='${{github.actor}}' --image-file='${{ github.event.inputs.image_url }}' --repetitions '${{github.event.inputs.repetitions}}' --connections '${{github.event.inputs.connections-per-cell}}' --repetition-delay '${{github.event.inputs.repetition-delay}}'
